### ISSUE TITLE
DE_list_DESeq2.tsv file missing

### ISSUE THREAD

**Issue by silviamorins** [qbicsoftware/rnadeseq#2]
It would be nice to have this file (list containing only the DE genes), together with the `final_list_DESeq2.tsv`, as output of the `DESeq.v2.7.R` script.

complete path: `DESeq2/zips/DESeq2/results/final/DE_list_DESeq2.tsv`

I would like to discuss this, though, before making a pull request.

**Comment by ggabernet** [comment]
If I understood it from the meeting today clearly, we would not add this table. We can bring it up in the next meeting still, though

**Comment by silviamorins** [comment]
I close this and put it in the agenda. I think the discussion ended somewhere else and there was not a clear point, but for now I'd drop it!
