### ISSUE TITLE
Report corrections

### ISSUE THREAD

**Issue by ggabernet** [qbicsoftware/rnadeseq#28]
- Section 3.2.1 Percentages tabs correct typos.
- go through the report text with Gisela
- headers for tables, show as space no dots (ask Marie)
- Mapping statistics: remove text about error rate.

**Comment by ggabernet** [comment]
@silviamorins is everything solved now by PR #30 ? Including the headers for tables, show as space no dots?

**Comment by silviamorins** [comment]
Yes, apart from the fact that we did not discuss the report text - but feel free to apply changes to it!

**Comment by ggabernet** [comment]
#32 should solve all the issues
