### ISSUE TITLE
No legenda on the .png output images

### ISSUE THREAD

**Issue by silviamorins** [qbicsoftware/rnadeseq#3]
In `DESeq2/results/plots` the `.png` pictures have no legenda, i.e. the sample names are not shown properly. In the corresponding `.pdf` files they are reported, but I fail to include these files in the report (i.e., they don't get shown).

**Comment by ggabernet** [comment]
Was this already solved by the new svg bug fix? Could you try to run locally the test profile?

**Comment by silviamorins** [comment]
.svgs shows legenda, great job! I would close this
