### ISSUE TITLE
filter columns on final table

### ISSUE THREAD

**Issue by ggabernet** [qbicsoftware/rnadeseq#7]
How to name and explain better the filter columns of the final table.

**Comment by ggabernet** [comment]
Suggestions:
- DE_in_contrast
- outcome
- Contrast_vector

DE / not-DE : filter

**Comment by silviamorins** [comment]
DE or not_DE: Outcome
1-0-... : Contrast_vector

the meaning of the contrast_vector's column needs to be explained in the report.

**Comment by ggabernet** [comment]
Also add explanation in the report.
